### ISSUE TITLE
JavaInvoke.callMethod fails forStringBuilder under Java 8

### ISSUE THREAD

**Issue by NonesuchRiver** [jtcl-project/jtcl#9]

**Comment by NonesuchRiver** [comment]
Hi -
   I recently upgraded from Java 6 to Java 8 and am now having scripts fail with the error message

                  "Return type AbstractStringBuilder is not accessible"

when using a Java StringBuilder in my script.  I'm guessing that this would happen if I was using a StringBuffer, since both StringBuilder and StringBuffer extend the package-private AbstractStringBuilder class.  The Janino folks ran into this problem (see the problem report at http://jira.codehaus.org/browse/JANINO-128).  Sadly, I don't know enough about the Java internals to suggest a fix (aside from the canonical "Don't do that" of course).

The solution for the Janino folks was to continue iterating through the list of methods looking for one that *was* accessible (they were looking for getLength(), found in both AbstractStringBuilder and in CharSequence).  I don't think that will work in this case.

   In the mean time, I'll go replace my use of StringBuilder with the TCL equivalents (append) and see what happens.

   Curses upon whoever thought extending from a package-private class was a good idea when most of the class' methods return itself.

**Comment by NonesuchRiver** [comment]
Didn't mean to close this ... sorry!

**Comment by tpoindex** [comment]
Ugly!  I never noticed this before, I assume this is it:

```
% package require java
2.0.0
% set sb [java::new StringBuilder foo]
java0x1
% $sb append bar
Return type "java.lang.AbstractStringBuilder" is not accessible
```

If you have a better test script, please attach.  I'll see if I can track down the Janino bug and fix, see if we can adapt it here.  Btw, if you have any fixes, don't hesitate to send them.

**Comment by NonesuchRiver** [comment]
Hi, Tom -
   Your test is as good as any.  The only fix I've been able to think of would be to hard code a test for where the "isAccessible() call is made, and this is really too ugly (not to mention that there might be other instances of this anti-pattern out there.  Sorry!

**Comment by tpoindex** [comment]
I did some digging and found where abstract super class methods were replacing methods in the subclass (StringBuilder, StringBuffer in particular) where these methods were returning the protected abstract class.  Added code to filter our methods that return non-accessible types, which seems to take care of the problem.  Java 6 & 7 also have the AbstractStringBuilder as a base class for StringBuilder, but probably didn't expose the problem, likely due to the ordering of how reflection methods are returned (??).

Please checkout, build and test.  If you still have problems, please re-open this issue.
